### PR TITLE
Environmental settings support

### PR DESCRIPTION
**Pull request by carlcs**

### CODE REVIEW

**Comment by lindseydiloreto** [comment]
Thanks @carlcs! It looks like this change would require users to be running Craft 3.1, is that correct?

**Comment by carlcs** [comment]
That’s correct, yes.

**Comment by lindseydiloreto** [comment]
Great, thanks for doing this!

I'm going to briefly hold off on merging this while I make a few other changes. I'd like for those changes to be available to folks who are still on Craft 3.0, before the plugin starts requiring 3.1.

Thanks again! 🍺

**Comment by lindseydiloreto** [comment]
This has been merged into the dev branch, and will be formally released within the next few weeks.

Thanks for making this possible @carlcs! Sorry it took so long to roll it back into the plugin. 🍺

**Pull request merged**
